[book]
title = "Srivenkateshwar"
authors = ["Srivenkateshwar"]
language = "en"
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Srivenkateshwar/vla"
